import type { EndpointDefinition, HostedMcpCatalog, HostedMcpTool, JsonSchema } from "./types.js";

export function generateEndpointTypes(endpoints: EndpointDefinition[], options: { namespace?: string } = {}): string {
  const namespace = options.namespace ?? "PremanEndpoints";
  const lines: string[] = [
    "/* eslint-disable */",
    "// Generated by preman-sdk. Do not edit by hand.",
    `export namespace ${namespace} {`,
  ];

  for (const endpoint of endpoints) {
    const name = typeName(endpoint);
    lines.push(`  export type ${name}Request = ${schemaToType(endpoint.requestBodySchema ?? endpoint.request_body_schema)};`);
    lines.push(`  export type ${name}Response = ${schemaToType(endpoint.responseSchema ?? endpoint.response_schema)};`);
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

export function generateHostedMcpToolTypes(
  catalog: HostedMcpCatalog,
  options: { namespace?: string; client?: boolean } = {},
): string {
  const namespace = options.namespace ?? "PremanTools";
  const tools = [...catalog.tools].sort((a, b) => a.name.localeCompare(b.name));
  const lines: string[] = [
    "/* eslint-disable */",
    "// Generated by preman-sdk. Do not edit by hand.",
    `export namespace ${namespace} {`,
  ];

  const toolNames = tools.map((tool) => JSON.stringify(tool.name)).join(" | ") || "never";
  lines.push(`  export type ToolName = ${toolNames};`);
  lines.push("  export type ToolArguments = {");
  for (const tool of tools) {
    const name = toolTypeName(tool);
    lines.push(`    ${JSON.stringify(tool.name)}: ${name}Args;`);
  }
  lines.push("  };");

  for (const tool of tools) {
    const name = toolTypeName(tool);
    const schema = tool.inputSchema ?? tool.input_schema;
    lines.push("");
    if (tool.description) {
      lines.push(`  /** ${tool.description.replace(/\*\//g, "* /")} */`);
    }
    lines.push(`  export type ${name}Args = ${schemaToType(schema)};`);
  }

  if (options.client) {
    lines.push("");
    lines.push("  export type ToolCaller = <Name extends ToolName>(name: Name, args: ToolArguments[Name]) => Promise<unknown>;");
    lines.push("  export function createClient(callTool: ToolCaller) {");
    lines.push("    return {");
    for (const tool of tools) {
      const method = clientMethodName(tool.name);
      const name = toolTypeName(tool);
      lines.push(`      ${method}: (args: ${name}Args) => callTool(${JSON.stringify(tool.name)}, args),`);
    }
    lines.push("    };");
    lines.push("  }");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function typeName(endpoint: EndpointDefinition): string {
  const method = title(endpoint.method.toLowerCase());
  const path = endpoint.path ?? endpoint.pathTemplate ?? endpoint.path_template ?? "endpoint";
  const parts = path.split("/").filter(Boolean).map((part) => title(part.replace(/[{}:_-]+/g, " ")));
  return `${method}${parts.join("") || "Root"}`.replace(/[^A-Za-z0-9_]/g, "");
}

function title(value: string): string {
  return value.split(/\s+/).filter(Boolean).map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join("");
}

export function schemaToType(schema: JsonSchema | undefined): string {
  if (!schema) return "unknown";

  if (schema["nullable"] === true) {
    return `${schemaToType({ ...schema, nullable: undefined })} | null`;
  }
  for (const key of ["anyOf", "oneOf"] as const) {
    const variants = schema[key];
    if (Array.isArray(variants) && variants.length) {
      return variants.map((item) => schemaToType(asSchema(item))).join(" | ");
    }
  }
  const allOf = schema["allOf"];
  if (Array.isArray(allOf) && allOf.length) {
    return allOf.map((item) => schemaToType(asSchema(item))).join(" & ");
  }
  if (schema["enum"] && Array.isArray(schema["enum"])) {
    return schema["enum"].map((value) => JSON.stringify(value)).join(" | ");
  }

  const type = schema["type"];
  if (Array.isArray(type)) {
    return type.map((item) => schemaToType({ ...schema, type: item })).join(" | ");
  }
  if (type === "string") return "string";
  if (type === "number" || type === "integer") return "number";
  if (type === "boolean") return "boolean";
  if (type === "null") return "null";
  if (type === "array") return `${schemaToType(asSchema(schema["items"]))}[]`;
  if (type === "object" || schema["properties"]) return objectSchemaToType(schema);
  if (schema["additionalProperties"]) return "Record<string, unknown>";
  return "unknown";
}

function objectSchemaToType(schema: JsonSchema): string {
  const properties = asObject(schema["properties"]);
  const additionalProperties = schema["additionalProperties"];
  if (!properties) {
    if (additionalProperties && typeof additionalProperties === "object" && !Array.isArray(additionalProperties)) {
      return `Record<string, ${schemaToType(additionalProperties as JsonSchema)}>`;
    }
    return "Record<string, unknown>";
  }
  const required = new Set(Array.isArray(schema["required"]) ? schema["required"].filter((item): item is string => typeof item === "string") : []);
  const fields = Object.entries(properties).map(([key, value]) => {
    const optional = required.has(key) ? "" : "?";
    return `${JSON.stringify(key)}${optional}: ${schemaToType(asSchema(value))};`;
  });
  const extra = additionalProperties && additionalProperties !== false
    ? [`[key: string]: ${typeof additionalProperties === "object" ? schemaToType(additionalProperties as JsonSchema) : "unknown"};`]
    : [];
  return `{\n${[...fields, ...extra].map((field) => `    ${field}`).join("\n")}\n  }`;
}

function asSchema(value: unknown): JsonSchema | undefined {
  return value && typeof value === "object" && !Array.isArray(value) ? value as JsonSchema : undefined;
}

function asObject(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
}

function toolTypeName(tool: HostedMcpTool): string {
  return title(tool.name.replace(/[^A-Za-z0-9_]+/g, " ").replace(/_/g, " ")) || "Tool";
}

function clientMethodName(name: string): string {
  const parts = name.replace(/[^A-Za-z0-9_]+/g, "_").split("_").filter(Boolean);
  const [first = "tool", ...rest] = parts;
  const candidate = `${first.toLowerCase()}${rest.map(title).join("")}`.replace(/[^A-Za-z0-9_$]/g, "");
  return /^[A-Za-z_$]/.test(candidate) ? candidate : `tool${title(candidate)}`;
}
